
task1:
  source:
    conn:
      host: localhost
      port: 3306
      db: agrim
      user: root
      pwd: ROOT@123@mysql
    get_query:    |
                    asf
                    asdf
  dest: 
    bucket: agrim-123
    file: s3_latest_price.csv

task2:
  skip: True