
task1:
  source:
    conn:
      host: localhost
      port: 3306
      db: agrim
      user: root
      pwd: ROOT@123@mysql
    get_query:    |
                    select product, status, price from product_status;
  source2: 
    bucket: agrim-123
    file_s3: s3_latest_price.csv
    file_loc: downloaded.csv
  dest:
    bucket: agrim-123
    file_s3: product
    file_loc: temp.csv